/*\
title: $:/plugins/ihm/tidgraph/utils.js
type: application/javascript
module-type: library

Internal utility functions for tidgraph plugin.

\*/
(function(){function u(b){var c=b.getBoundingClientRect(),a=document.body,d=document.documentElement,e=c.top-(b.scrollTop||window.pageYOffset||d.scrollTop||a.scrollTop)-(d.clientTop||a.clientTop||0);b=c.left-(b.scrollLeft||window.pageXOffset||d.scrollLeft||a.scrollLeft)-(d.clientLeft||a.clientLeft||0);return{top:e,left:b,width:c.width,height:c.height,right:b+c.width,bottom:e+c.height}}function x(b,c,a){var d;b=u(b);if("string"===typeof a){if(d=document.querySelector(a),null==d)return null}else a instanceof
HTMLElement&&(d=a);var e=u(d);a=e.bottom-b.top;d=e.left-b.left;var g=e.right-b.left;b=e.top-b.top;e="";switch(c.toUpperCase()){case "L":e=[Math.round(d),Math.round(a/2+b/2)];break;case "R":e=[Math.round(g),Math.round(a/2+b/2)];break;case "T":e=[Math.round(g/2+d/2),Math.round(b)];break;case "B":e=[Math.round(g/2+d/2),Math.round(a)]}return e}function v(b){return'<span style="color:green">vecmap:</span><span style="color:red">'+b+"</span>"}function y(b,c,a){var d;d=u(c);var e=u(a);d=4>e.left+e.width/
2-(d.left+d.width/2)?["R","R"]:["R","L"];e=x(b,d[0],c);b=x(b,d[1],a);var g,f,h=10;if(null==c||null==a)return v("can't connect null element");if(null==e)return v("port not found for "+c.tagName+" - "+c.innerHTML);if(null==b)return v("port not found for "+a.tagName+" - "+a.innerHTML);c=Math.abs(b[1]-e[1]);b[1]>e[1]&&(g=c/2);b[1]<e[1]&&(g=-c/2);5>c&&(g=0);"L"==d[1]&&(f=-10);"R"==d[1]&&(f=10,h=20);return'<path d="M'+e[0]+","+e[1]+" Q"+(e[0]+h)+","+e[1]+"  "+(e[0]+h)+","+(e[1]+g)+" Q"+(e[0]+h)+","+b[1]+
"  "+(b[0]+f)+","+b[1]+'" marker-end="url(#tgr-arrow)"/>'}function w(b,c){var a;switch(c.mode.toLowerCase()){case "tagging":a="[["+b+"]tagging[]]+"+c.filter;a=$tw.wiki.filterTiddlers(a);break;case "linking":a="[["+b+"]links[]!is[missing]]+"+c.filter,a=$tw.wiki.filterTiddlers(a)}return a}function z(b,c,a){switch(a.mode.toLowerCase()){case "tagging":return(a=$tw.wiki.getTiddler(b))?a.hasTag(c):!1;default:return a=w(c,a),-1!==a.indexOf(b)}}function A(b,c){function a(a,p){f=p;h=a;n=encodeURIComponent(f);
k=encodeURIComponent(h);e=document.getElementById(c.id+"-"+n);g=document.getElementById(c.id+"-"+k);e&&g&&d.push(y(b,e,g))}var d=[],e,g,f,h,n,k;q(c.root,function(b,c,d){(c=b.parent)&&a(b.id,c.id)},{},{skipvisited:!0});for(var l=c.outliers.length,m=0;m<l;m++)a(c.outliers[m][0],c.outliers[m][1],!0);return d.join(" ")}function q(b,c,a,d){d=d||{};var e=d.done||[],g=d.getCh||function(a){return a.collapse?[]:a.children},f=d.lvl||0,h=void 0===d.skipvisited?!0:d.skipvisited;d.leave=d.leave||!1;if(h&&-1!==
e.indexOf(b))return a;e.push(b);g=g(b);h=g.length;a=a||{};d.lvl=f+1;d.done=e;if(!1===c(b,a,f))return d.leave=!0,a;for(b=0;b<h;b++)if(a=q(g[b],c,a,d),d.leave)return a;d.lvl--;return a}function B(b,c,a,d){d=d||{};var e=d.getCh||function(a){return a.collapse?[]:a.children},g=d.getId||function(a){return a.id},f=void 0===d.skipvisited?!0:d.skipvisited,h=d.maxdepth||-1;a=a||{};var n=[],k=[],l=[],m=0;n.push(b);l[g(b)]=void 0;do{b=n.length;for(var r=0;r<b;r++){var p=n.shift(),t;t=f?-1===k.indexOf(p)?!1:!0:
!1;if(!t&&!1===c(p,l[g(p)],a))return a;k.push(p);t=e(p);n=n.concat(t);t&&t.forEach(function(a){var b=l[g(a)];b?g(b)!==g(p)&&d.outlier&&d.outlier(a,p):l[g(a)]=p})}m++}while(0!==n.length&&m<=h);return a}function C(b,c){return q(b,function(a,b){b.cnt++;return!0},{cnt:0},{skipvisited:c}).cnt-1}function r(b,c,a){if(!(this instanceof r))throw"Error: call new tnode(id="+c+")";this.parent=b;this.id=c;this.children=[];this.collapse=!1;this.widget=a}exports.buildTable=function(b,c){function a(a,b){return $tw.utils.domMaker(a,
$tw.utils.extend(b,{document:c.document}))}c.id=(new Date).valueOf();var d=a("table",{"class":"ihm-tgr-table",attributes:{id:c.id+"-table"}});(function(b){var d=$tw.wiki;q(c.root,function(f,h,n){var k=d.getTiddler(f.id);h=1+C(f,!0);var l=encodeURIComponent(f.id),m;if(k){m=$tw.utils.parseStringArray(c.tooltip);for(var r=m.length,p="",t=0;t<r&&!(p=k.getFieldString(m[t]));t++);m=p}else m="";var q;k&&(q=c.nodetitle?k.getFieldString(c.nodetitle):k.hasField("caption")?k.fields.caption:k.fields.title);n>=
c.startat&&(n=a("a",{"class":"tc-tiddlylink tc-tiddlylink-resolves",text:q,attributes:{href:"#"+l}}),!1===c.nocollapse&&f.children&&0<f.children.length?(q=a("a",{"class":"ihm-tgr-collapse tc-tiddlylink",text:f.collapse?"\u2295":"\u2296"}),$tw.utils.addEventListeners(q,[{name:"click",handlerObject:f,handlerMethod:"collapseClickEvent"}]),f=a("div",{"class":"ihm-tgr-node tgr-node",children:[n,q],attributes:{id:c.id+"-"+l,title:m}})):f=a("div",{"class":"ihm-tgr-node tgr-node",children:[n],attributes:{id:c.id+
"-"+l,title:m}}),f=a("td",{attributes:{rowspan:h},children:[f]}),f=a("tr",{children:[f]}),b.appendChild(f))},{},{skipvisited:!0})})(d);return d};exports.buildSVG=function(b,c){var a=document.getElementById(c.id+"-table");if(a)return getComputedStyle(a),'<svg  xmlns="http://www.w3.org/2000/svg" height="'+b.offsetHeight+'px" width="'+b.offsetWidth+'px" style="overflow: visible"><defs> <marker id="tgr-arrow" viewBox="0 0 10 10" refX="1" refY="5" markerUnits="strokeWidth" orient="auto" markerWidth="8" markerHeight="6"> <polyline class="ihm-tgr-arrow tgr-arrow" points="0,0 10,5 0,10 0,5" style="opacity:1;" /></marker></defs> <g class="ihm-tgr-link tgr-link" style="overflow: visible"> '+
A(b,c)+"</g> </svg>"};exports.isDescendant=function(b,c,a){if(z(b,c,a))return!0;var d=!1;q(c,function(a,c,f){if(a===b)return d=!0,!1},{},{skipvisited:!0,getCh:function(b){return w(b,a)}});return d};exports.makeTidTree=function(b,c,a){a=a||{};var d=!1;c.outliers=[];var e=new r(void 0,b,a.widget);B(b,function(b,c,d){if(c){a:{for(var e=d.visited,k=e.length,l=0;l<k;l++)if(e[l].id===c){c=e[l];break a}c=void 0}b=c.addChild(b,a.widget);d.visited.push(b)}return!0},{visited:[e]},{getId:function(a){return a},
getCh:function(a){return w(a,c)},maxdepth:c.maxdepth,skipvisited:!0,outlier:function(a,b){d=!1;$tw.utils.each(c.outliers,function(c){c[0]===a&&c[1]===b&&(d=!0)});d||c.outliers.push([a,b])}});return e};r.prototype.addChild=function(b,c){var a=new r(this,b,c);this.children.push(a);return a};r.prototype.toString=function(){return"tnode(id="+this.id+")"};r.prototype.collapseClickEvent=function(b){this.collapse=!this.collapse;console.log(this.id+" collapse=",this.collapse,this.widget);this.widget.paint()}})();
