/*\
title: $:/plugins/ihm/tidgraph/utils.js
type: application/javascript
module-type: library

Internal utility functions for tidgraph plugin.

\*/
(function(){function u(d){var b=d.getBoundingClientRect(),a=document.body,c=document.documentElement,e=b.top-(d.scrollTop||window.pageYOffset||c.scrollTop||a.scrollTop)-(c.clientTop||a.clientTop||0);d=b.left-(d.scrollLeft||window.pageXOffset||c.scrollLeft||a.scrollLeft)-(c.clientLeft||a.clientLeft||0);return{top:e,left:d,width:b.width,height:b.height,right:d+b.width,bottom:e+b.height}}function y(d,b,a){var c;d=u(d);if("string"===typeof a){if(c=document.querySelector(a),null==c)return null}else a instanceof
HTMLElement&&(c=a);var e=u(c);a=e.bottom-d.top;c=e.left-d.left;var f=e.right-d.left;d=e.top-d.top;e="";switch(b.toUpperCase()){case "L":e=[Math.round(c),Math.round(a/2+d/2)];break;case "R":e=[Math.round(f),Math.round(a/2+d/2)];break;case "T":e=[Math.round(f/2+c/2),Math.round(d)];break;case "B":e=[Math.round(f/2+c/2),Math.round(a)]}return e}function w(d){return'<span style="color:green">vecmap:</span><span style="color:red">'+d+"</span>"}function z(d,b,a){var c;c=u(b);var e=u(a);c=4>e.left+e.width/
2-(c.left+c.width/2)?["R","R"]:["R","L"];e=y(d,c[0],b);d=y(d,c[1],a);var f,g,h=10;if(null==b||null==a)return w("can't connect null element");if(null==e)return w("port not found for "+b.tagName+" - "+b.innerHTML);if(null==d)return w("port not found for "+a.tagName+" - "+a.innerHTML);b=Math.abs(d[1]-e[1]);d[1]>e[1]&&(f=b/2);d[1]<e[1]&&(f=-b/2);5>b&&(f=0);"L"==c[1]&&(g=-10);"R"==c[1]&&(g=10,h=20);return'<path d="M'+e[0]+","+e[1]+" Q"+(e[0]+h)+","+e[1]+"  "+(e[0]+h)+","+(e[1]+f)+" Q"+(e[0]+h)+","+d[1]+
"  "+(d[0]+g)+","+d[1]+'" marker-end="url(#vm-arrow)"/>'}function x(d,b){var a;switch(b.mode.toLowerCase()){case "tagging":a="[["+d+"]tagging[]]+"+b.filter;a=$tw.wiki.filterTiddlers(a);break;case "linking":a="[["+d+"]links[]!is[missing]]+"+b.filter,a=$tw.wiki.filterTiddlers(a)}return a}function A(d,b){function a(a,l){g=l;h=a;k=escape(g);m=escape(h);e=document.getElementById(b.id+"-"+k);f=document.getElementById(b.id+"-"+m);e&&f&&c.push(z(d,e,f))}var c=[],e,f,g,h,k,m;v(b.root,function(c,b,d){(b=c.parent)&&
a(c.id,b.id)},{},{skipvisited:!1});for(var p=b.outliers.length,n=0;n<p;n++)a(b.outliers[n][0],b.outliers[n][1],!0);return c.join(" ")}function v(d,b,a,c){c=c||{};var e=c.done||[],f=c.getCh||function(c){return c.children},g=c.lvl||0,h=void 0===c.skipvisited?!0:c.skipvisited;c.leave=c.leave||!1;if(h&&-1!==e.indexOf(d))return a;e.push(d);f=f(d);h=f.length;a=a||{};c.lvl=g+1;c.done=e;if(!1===b(d,a,g))return c.leave=!0,a;for(d=0;d<h;d++)if(a=v(f[d],b,a,c),c.leave)return a;c.lvl--;return a}function B(d,
b,a,c){c=c||{};var e=c.getCh||function(c){return c.children},f=c.getId||function(c){return c.id},g=void 0===c.skipvisited?!0:c.skipvisited,h=c.maxdepth||-1;a=a||{};var k=[],m=[],p=[],n=0;k.push(d);p[f(d)]=void 0;do{d=k.length;for(var q=0;q<d;q++){var l=k.shift(),r;r=g?-1===m.indexOf(l)?!1:!0:!1;if(!r&&!1===b(l,p[f(l)],a))return a;m.push(l);r=e(l);k=k.concat(r);r&&r.forEach(function(a){var b=p[f(a)];b?f(b)!==f(l)&&c.outlier&&c.outlier(a,l):p[f(a)]=l})}n++}while(0!==k.length&&n<=h);return a}function C(d,
b,a){b.outliers=[];a=new t(void 0,d,!1);B(d,function(c,a,b){if(a){a:{for(var d=b.visited,h=d.length,k=0;k<h;k++)if(d[k].id===a){a=d[k];break a}a=void 0}c=a.addChild(c,!1);b.visited.push(c)}return!0},{visited:[a]},{getId:function(a){return a},getCh:function(a){return x(a,b)},maxdepth:b.maxdepth,skipvisited:!0,outlier:function(a,d){b.outliers.push([a,d])}});return a}function D(d,b){return v(d,function(a,c){c.cnt++;return!0},{cnt:0},{skipvisited:b}).cnt-1}function t(d,b,a){if(!(this instanceof t))throw"Error: call new tnode(id="+
b+")";this.parent=d;this.id=b;this.children=[]}exports.buildTable=function(d,b){var a;b.id=(new Date).valueOf();b.root=C(d,b);a={str:'<table id="'+b.id+'-table">'};(function(a){var d=$tw.wiki;v(b.root,function(f,g,h){g=d.getTiddler(f.id);var k=1+D(f,b);f=escape(f.id);var m;if(g){m=$tw.utils.parseStringArray(b.tooltip);for(var p=m.length,n="",q=0;q<p&&!(n=g.getFieldString(m[q]));q++);m=n}else m="";var l;g&&(l=b.nodetitle?g.getFieldString(b.nodetitle):g.hasField("caption")?g.fields.caption:g.fields.title);
h>=b.startat&&(a.str=a.str+'<tr><td  rowspan="'+k+'">'+('<a class="tc-tiddlylink tc-tiddlylink-resolves ihm-tgr-node tgr-node"  href="#'+f+'" id="'+b.id+"-"+f+'"  title="'+m+'">'+l+"</a>")+"</td></tr>")},a,{skipvisited:!0})})(a);a.str+="</table>";console.log("outliers=",b.outliers);return a.str};exports.buildSVG=function(d,b){var a=document.getElementById(b.id+"-table");if(a)return a=a.getBoundingClientRect(),'<svg  xmlns="http://www.w3.org/2000/svg" height="'+a.height+'px" width="'+a.width+'px" style="overflow: visible"> <defs> <marker id="vm-arrow" viewBox="0 0 10 10" refX="1" refY="5" markerUnits="strokeWidth" orient="auto" markerWidth="8" markerHeight="6"> <polyline class="ihm-tgr-arrow tgr-arrow" points="0,0 10,5 0,10 0,5" style="opacity:1;"/></marker><marker id="vm-circle" viewBox="-25 0 50 50" refX="0" refY="0" markerUnits="strokeWidth" orient="0" markerWidth="50" markerHeight="50"> <text x = "-10" y = "12.5" fill = "navy" font-size = "15">  It was the best of times </text> <rect x="-15" y="0" width="30" height="15" rx="0px" ry="0px" style="opacity:0.5" /> <circle cx="1" cy="5" r="1" stroke="darkblue" stroke-width="1" fill="red" /> </marker> </defs> <g class="ihm-tgr-link tgr-link"  height="'+
a.height+'px" width="'+a.width+'px" style="overflow: visible"> '+A(d,b)+"</g> </svg>"};exports.isDescendant=function(d,b,a){var c;a:switch(a.mode.toLowerCase()){case "tagging":c=(c=$tw.wiki.getTiddler(d))?c.hasTag(b):!1;break a;default:c=x(b,a),c=-1!==c.indexOf(d)}if(c)return!0;b=x(b,a);c=b.length;for(var e=!1,f=0;f<c&&!(e=exports.isDescendant(d,b[f],a));f++);return e};t.prototype.addChild=function(d,b){var a=new t(this,d,b);this.children.push(a);return a};t.prototype.toString=function(){return"tnode(id="+
this.id+")"}})();
