/*\
title: $:/plugins/ihm/widgets/tidgraph.js
type: application/javascript
module-type: widget

Tidgraph widget to render HTML5/SVG graph of tiddlers

\*/
(function(){var e=require("$:/core/modules/widgets/widget.js").widget,b=function(c,f){this.initialise(c,f)},d=require("$:/plugins/ihm/tidgraph/utils.js");b.prototype=new e;b.prototype.render=function(c,f){this.parentDomNode=c;this.nextSiblingDomNode=f;this.computeAttributes();this.execute();this.tidtree=[];this.tidtree.mode=this.mode;this.tidtree.maxdepth=this.maxdepth;this.tidtree.startat=this.startat;this.tidtree.nodetitle=this.nodetitle;this.tidtree.tooltip=this.tooltip;this.tidtree.filter=this.filter;
this.tidtree.nocollapse=this.nocollapse;this.tidtree.document=this.document;this.div=this.document.createElement("div");this.div.className="tgr-container tgr";this.tablediv=this.document.createElement("div");this.tablediv.className="ihm-tgr-tablediv";this.table=void 0;this.div.appendChild(this.tablediv);this.svgdiv=this.document.createElement("div");this.svgdiv.className="tgr-svg-int";this.div.appendChild(this.svgdiv);this.parentDomNode.insertBefore(this.div,this.nextSiblingDomNode);this.domNodes.push(this.div);
this.tidtree.root=d.makeTidTree(this.startTid,this.tidtree,{widget:this});this.paint();var a=this,b=function(){a.svgdiv.innerHTML=d.buildSVG(a.tablediv,a.tidtree);a.oldresize&&a.oldresize()},e=function(){a.svgdiv.innerHTML=d.buildSVG(a.tablediv,a.tidtree)};this.div.onscroll=function(){a.scroll_to||clearTimeout(a.scroll_to);a.scroll_to=setTimeout(e,100)};this.onresize_updated||(window.onresize&&void 0==this.oldresize&&(this.oldresize=window.onresize),window.onresize=function(){a.resize_to||clearTimeout(a.resize_to);
a.resize_to=setTimeout(b,100)},this.onresize_updated=!0)};b.prototype.paint=function(){this.sidebar=$tw.wiki.getTiddlerText("$:/state/sidebar");var c=d.buildTable(this.startTid,this.tidtree);this.table?this.tablediv.replaceChild(c,this.table):this.tablediv.appendChild(c);this.svgdiv.innerHTML=d.buildSVG(this.tablediv,this.tidtree);this.table=c};b.prototype.execute=function(){this.startTid=this.getAttribute("start");this.mode=this.getAttribute("mode","tagging").toLowerCase();this.maxdepth=parseInt(this.getAttribute("maxdepth",
"10"));this.startat=this.getAttribute("startat","0");this.nodetitle=this.getAttribute("nodetitle");this.tooltip=this.getAttribute("tooltip","summary");this.filter=this.getAttribute("filter","[!is[system]]");this.nocollapse=this.hasAttribute("nocollapse");-1==["tagging","linking"].indexOf(this.mode)&&(this.mode="tagging")};b.prototype.refresh=function(c){var b=!1,a;this.computeAttributes();this.execute();for(a in c)if(document.getElementById(this.tidtree.id+"-"+escape(a))||d.isDescendant(a,this.startTid,
this.tidtree)){b=!0;break}$tw.wiki.getTiddlerText("$:/state/sidebar")!==this.sidebar&&(b=!0);return b?(this.refreshSelf(),!0):!1};exports.tidgraph=b})();
